openapi: '3.0.1'
info:
  title: Grafana Backup
  version: '0.0.0'
  description: Ferramenta utilizada para fazer backup dos dashboards exibidos no Grafana
paths:
  /dashboard:       
    post: 
      summary: 'Vai conectar no grafana passado, listar todos os dashaboards e salva-los'
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/Grafana'
      responses:              
        '200':
          description: vai passar a quantidade de dashboards salvos
components:
  schemas:
    Grafana:
      properties:
        url:
          type: string
        login:
          type: string
        password:
          type: string
      required:
        - url
        - login
        - password
      type: object

   

